"""
Code generator.

Walks the AST and emits virtual-machine assembly text.
The output is architecture-independent; it uses the VM instruction set
(LIT, CALL, EXIT, ZBRANCH, etc.) which are later resolved to native
instructions by the target-specific macro file (vmachine.inc).

The generator also tracks:
  - a symbol table of constants and word names
  - a label counter for synthetic branch targets
  - a string literal pool (emitted at end of each word)

Name mangling
-------------
Forth allows characters in word names (-, ?, !, @, etc.) that are illegal
in most assembler label identifiers.  _mangle() translates them to safe
ASCII equivalents before any name is emitted as a label or symbol.

  -   →  _          (most common: hyphenated-words)
  ?   →  _q
  !   →  _st         (store)
  @   →  _ft         (fetch)
  >   →  _to
  <   →  _lt
  =   →  _eq
  +   →  _pl
  *   →  _st2        (star — already used _st for !, so use _mul)
  /   →  _sl
  .   →  _dot
  #   →  _hash
  '   →  _tick

Any other non-alphanumeric/underscore character becomes _xNN (hex code).
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import TextIO
import io
import re

from .ast_nodes import (
    Program, CreateDef, ConstantDef, VariableDef, WordDef,
    DefineDirective, ExportDirective, OriginDirective, SegmentDirective,
    MainDirective, NumberLit, StringLit, PrintString,
    WordCall, IfThen, BeginUntil, BeginWhileRepeat,
    DoLoop, ASTNode,
)

@dataclass
class CompileResult:
    asm:     str        # generated assembly text
    exports: list       # original Forth names of exported words
    inc:     str        # companion .inc content, empty if no exports


def _generate_inc(stem: str, exports: list) -> str:
    """Generate companion .inc file content for exported symbols."""
    guard = f'__{stem}__'
    lines = [
        '; Auto-generated by forthc — do not edit by hand',
        f'.ifndef {guard}',
        f'{guard} = 1',
    ]
    for word in sorted(exports):
        lines.append(f'        .import {_mangle(word)}')
    lines.append('.endif')
    lines.append('')
    return '\n'.join(lines)


def generate(program: Program, stem: str = '', out: TextIO | None = None) -> CompileResult:
    buf = io.StringIO()
    cg  = CodeGenerator(out=buf, stem=stem)
    text = cg.generate(program)
    if out is not None:
        out.write(text)
    exports = sorted(cg._exports)
    inc = _generate_inc(stem, exports) if exports else ''
    return CompileResult(asm=text, exports=exports, inc=inc)


# ---------------------------------------------------------------------------
# Name mangling
# ---------------------------------------------------------------------------

def _to_u16(value: int) -> int:
    """Convert a signed integer to its 16-bit two's complement unsigned form.
    CA65 does not accept negative constants, so -1 must be emitted as $FFFF."""
    if value < 0:
        return value & 0xFFFF
    return value

_MANGLE_MAP = {
    '-': '_',
    '?': '_q',
    '!': '_store',
    '@': '_fetch',
    '>': '_to',
    '<': '_from',
    '=': '_eq',
    '+': '_pl',
    '*': '_mul',
    '/': '_sl',
    '.': '_dot',
    '#': '_hash',
    "'": '_tick',
}

def _mangle(name: str) -> str:
    """Translate a Forth word name to a valid assembler identifier."""
    out = []
    for ch in name:
        if ch.isalnum() or ch == '_':
            out.append(ch)
        elif ch in _MANGLE_MAP:
            out.append(_MANGLE_MAP[ch])
        else:
            out.append(f'_x{ord(ch):02x}')
    result = ''.join(out)
    # Identifiers must not start with a digit
    if result and result[0].isdigit():
        result = '_' + result
    return result


# ---------------------------------------------------------------------------
# Built-in word → VM instruction mapping
# ---------------------------------------------------------------------------
# Words that compile directly to a single VM instruction (no CALL needed).

INLINE_OPS: dict[str, str] = {
    '@':      'FETCH',
    '!':      'STORE',
    'c@':     'BFETCH',
    'c!':     'BSTORE',
    '>r':     'TOR',
    'r>':     'RFROM',
    'r@':     'RTOS',
    'i':      'RTOS',
    '2>r':    'TWOTOR',
    '2r>':    'TWORFROM',
    'dup':    'DUP',
    '?dup':   'QDUP',
    'drop':   'DROP',
    'nip':    'NIP',
    'abs':    'ABS',
    'invert': 'INVERT',
    '1+':     'ONEPLUS',
    '1-':     'ONEMINUS',
    '2*':     'TWOSTAR',
    '2/':     'TWOSLASH',
    '+':      'ADD',
    '-':      'SUB',
    '*':      'STAR',
    '=':      'EQ',
    'clear':  'CLEAR',
}

# Words that require a call to a runtime routine.
RUNTIME_CALLS: dict[str, str] = {
    'base':   'vm_base_addr',
    'um*':    'vm_umstar',
    'um/mod': 'vm_umslashmod',
    'sm/rem': 'vm_smrem',
    'fm/mod': 'vm_fmmod',
    'and':    'vm_and',
    'or':     'vm_or',
    'xor':    'vm_xor',
    'lshift': 'vm_lshift',
    'rshift': 'vm_rshift',
    '<>':     'vm_neq',
    '<':      'vm_lt',
    '>':      'vm_gt',
    'u<':     'vm_ult',
    'u>':     'vm_ugt',
    'u<=':    'vm_ule',
    'u>=':    'vm_uge',
    '0=':     'vm_zeq',
    '0<>':    'vm_zne',
    '0<':     'vm_zlt',
    '0>':     'vm_zgt',
    'over':   'vm_over',
    'swap':   'vm_swap',
    'pick':   'vm_pick',
    'rot':    'vm_rot',
    '-rot':   'vm_mrot',
    'roll':   'vm_roll',
    '2@':     'vm_2fetch',
    '2!':     'vm_2store',
    '2dup':   'vm_2dup',
    '2swap':  'vm_2swap',
    '2over':  'vm_2over',
    'j':      'vm_j',
    'allot':  'vm_allot',
    'here':   'vm_here',
    'count':  'vm_count',
    'move':   'vm_move',
    'fill':   'vm_fill',
    'depth':  'vm_depth',
    '.s':     'vm_dots',
    'tuck':   'vm_tuck',
    'd+':     'vm_dplus',
    'd-':     'vm_dminus',
    'dabs':   'vm_dabs',
    'dnegate': 'vm_dnegate',
    'd=':     'vm_deq',
    'du<':    'vm_dult',
    'd<':     'vm_dlt',
    'execute': 'vm_execute',
    'cr':     'vm_cr',
    'space':  'vm_space',
    'spaces': 'vm_spaces',
    '.':      'vm_dot',
    'u.':     'vm_udot',
    '.hex':   'vm_dothex',
    'cputs':  'vm_cputs',
    'emit':   'vm_emit',
    'key':    'vm_key',
    'type':   'vm_type',
    'hld':    'vm_hld_addr',
    'pad-end': 'vm_pad_end_addr',
}

class CodeGenError(Exception):
    def __init__(self, msg, node: ASTNode | None = None):
        if node:
            super().__init__(f"Line {node.line}, col {node.col}: {msg}")
        else:
            super().__init__(msg)
        self.node = node


@dataclass
class CodeGenerator:
    out:          TextIO = field(default_factory=io.StringIO)
    stem:         str    = ''
    _label_count: int    = field(default=0, init=False)
    _constants:   dict   = field(default_factory=dict, init=False)
    _creates:     set    = field(default_factory=set, init=False)
    _variables:   set    = field(default_factory=set, init=False)
    _words:       set    = field(default_factory=set, init=False)
    _exports:     set    = field(default_factory=set, init=False)
    _defines:     set    = field(default_factory=set, init=False)
    _str_count:   int    = field(default=0, init=False)
    _entry_word:  object = field(default=None, init=False)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------
    def generate(self, program: Program) -> str:
        # collect DefineDirective symbols for pre-pass
        self._defines = {n.symbol for n in program.definitions
                         if isinstance(n, DefineDirective)}
        # Pre-pass: find MainDirective and ExportDirectives
        mains = [n for n in program.definitions if isinstance(n, MainDirective)]
        if len(mains) > 1:
            raise CodeGenError("Only one .main directive is allowed")
        self._entry_word = mains[0].word if mains else None
        self._exports = {n.word for n in program.definitions
                         if isinstance(n, ExportDirective)}
        self._emit_file_header()
        for node in program.definitions:
            self._top_def(node)
        self._emit_file_footer()
        if isinstance(self.out, io.StringIO):
            return self.out.getvalue()
        return ''

    # ------------------------------------------------------------------
    # Emit helpers
    # ------------------------------------------------------------------

    def _emit(self, line: str = ''):
        print(line, file=self.out)

    def _emit_instr(self, instr: str, comment: str = ''):
        if comment:
            self._emit(f'    {instr:<20} ; {comment}')
        else:
            self._emit(f'    {instr}')

    def _emit_label(self, label: str):
        self._emit(f'{label}:')

    def _fresh_label(self, prefix='L') -> str:
        self._label_count += 1
        return f'{prefix}_{self._label_count:04d}'

    # ------------------------------------------------------------------
    # File-level boilerplate
    # ------------------------------------------------------------------

    def _emit_file_header(self):
        self._emit('; Generated by forthc — do not edit by hand')
        self._emit()
        self._emit('; ca65 / 65816 mode — must appear before any .include')
        self._emit('        .p816')
        self._emit('        .smart  off')
        self._emit('        .A16')
        self._emit('        .I16')
        self._emit()
        # Guard symbols must come before .include so .ifndef guards fire correctly
        if self.stem:
            self._emit(f'__{self.stem}__ = 1')
            self._emit()

        for sym in sorted(self._defines):
            self._emit(f'{sym} = 1')
        if self._defines:
            self._emit()
        self._emit('.include "vmachine.inc"')
        self._emit()

    def _emit_file_footer(self):
        self._emit()
        self._emit('; === end of generated code ===')

    # ------------------------------------------------------------------
    # Top-level definitions
    # ------------------------------------------------------------------

    def _top_def(self, node: ASTNode):
        if isinstance(node, CreateDef):
            self._gen_create(node)
        elif isinstance(node, ConstantDef):
            self._gen_constant(node)
        elif isinstance(node, VariableDef):
            self._gen_variable(node)
        elif isinstance(node, WordDef):
            self._gen_word(node)
        elif isinstance(node, DefineDirective):
            pass    # emitted before .include in _emit_file_header
        elif isinstance(node, ExportDirective):
            pass    # handled in pre-pass; _gen_word emits the .export
        elif isinstance(node, OriginDirective):
            self._gen_origin(node)
        elif isinstance(node, SegmentDirective):
            self._gen_segment(node)
        elif isinstance(node, MainDirective):
            self._gen_main(node)
        else:
            raise CodeGenError(f"Unknown top-level node {type(node).__name__}", node)

    def _gen_create(self, node: CreateDef):
        sym = _mangle(node.name)

        # self._emit(f'; create {node.name}')
        comment = f'create {node.name}' + (f' {node.size} allot' if node.size else '')
        self._emit(f'; {comment}')
        self._emit_label(sym)
        if node.size > 0:
            self._emit(f'    .res {node.size}')
        self._emit()
        self._creates.add(node.name)

    def _gen_constant(self, node: ConstantDef):
        sym = _mangle(node.name)
        self._emit(f'; constant {node.name}')
        self._emit(f'{sym} = ${_to_u16(node.value):04X}')
        self._emit()
        self._constants[node.name] = node.value

    def _gen_variable(self, node: VariableDef):
        sym = _mangle(node.name)
        self._emit(f'; variable {node.name}')
        self._emit_label(sym)
        self._emit_instr('.word 0', f'storage for variable {node.name}')
        self._emit()
        self._variables.add(node.name)

    def _gen_word(self, node: WordDef):
        self._words.add(node.name)
        sym = _mangle(node.name)
        self._emit(f'; word definition: {node.name}')
        if node.name == self._entry_word or node.name in self._exports:
            self._emit(f'.export {sym}')
        self._emit_label(sym)
        str_pool: list[tuple[str, str]] = []
        self._gen_body(node.body, str_pool)
        self._emit_instr('EXIT', 'return from word')
        for lbl, text in str_pool:
            self._emit_label(lbl)
            escaped = text.replace('"', '\\"')
            self._emit(f'    .byte "{escaped}", 0')
        self._emit()

    def _gen_main(self, node: MainDirective):
        sym = _mangle(node.word)
        self._emit(f'; .main: export entry word for vmachine.s MAIN proc')
        self._emit(f'forth_main = {sym}')
        self._emit('.export forth_main')
        self._emit()

    def _gen_origin(self, node: OriginDirective):
        self._emit(f'; .origin ${node.address:X} — placement is controlled by the linker config')
        self._emit()

    def _gen_segment(self, node: SegmentDirective):
        self._emit(f'.segment "{node.name}"')
        self._emit()

    # ------------------------------------------------------------------
    # Body code generation
    # ------------------------------------------------------------------

    def _gen_body(self, stmts: list, str_pool: list):
        for stmt in stmts:
            self._gen_stmt(stmt, str_pool)

    def _gen_stmt(self, node: ASTNode, str_pool: list):
        if isinstance(node, NumberLit):
            u16 = _to_u16(node.value)
            self._emit_instr(f'LIT ${u16:04X}', f'push {node.value}')
        elif isinstance(node, StringLit):
            lbl = self._fresh_str_label()
            str_pool.append((lbl, node.text))
            self._emit_instr(f'LIT {lbl}',            'push string address')
            self._emit_instr(f'LIT {len(node.text)}', 'push string length')

        elif isinstance(node, PrintString):
            lbl = self._fresh_str_label()
            str_pool.append((lbl, node.text))
            self._emit_instr(f'LIT {lbl}', f'print: "{node.text[:30]}"')
            self._emit_instr('CALL vm_cputs',    'print null-terminated string')

        elif isinstance(node, WordCall):
            self._gen_word_call(node)

        elif isinstance(node, IfThen):
            self._gen_if(node, str_pool)

        elif isinstance(node, BeginUntil):
            self._gen_begin_until(node, str_pool)

        elif isinstance(node, BeginWhileRepeat):
            self._gen_begin_while_repeat(node, str_pool)

        elif isinstance(node, DoLoop):
            self._gen_do_loop(node, str_pool)

        else:
            raise CodeGenError(f"Unknown statement node {type(node).__name__}", node)

    def _gen_word_call(self, node: WordCall):
        name = node.name

        # Inline VM primitive?
        if name in INLINE_OPS:
            instr = INLINE_OPS[name]
            self._emit_instr(instr, f'( {name} )')
            return

        # Runtime call?
        if name in RUNTIME_CALLS:
            target = RUNTIME_CALLS[name]
            self._emit_instr(f'CALL {target}', f'( {name} )')
            return

        # Known constant — compile-time fold to LIT
        if name in self._constants:
            val = self._constants[name]
            self._emit_instr(f'LIT {val}', f'constant {name} = {val}')
            return

        # Variable or create — push its address
        if name in self._variables or name in self._creates:
            sym = _mangle(name)
            self._emit_instr(f'LIT {sym}', f'address of {name}')
            return

        # Known user-defined — word mangle the name
        sym = _mangle(name)
        self._emit_instr(f'CALL {sym}', f'call {name}')

    # ------------------------------------------------------------------
    # Control structures
    # ------------------------------------------------------------------

    def _gen_if(self, node: IfThen, str_pool: list):
        else_lbl = self._fresh_label('else')
        end_lbl  = self._fresh_label('endif')

        self._emit_instr(f'ZBRANCH {else_lbl}', 'if: branch if zero (false)')
        self._gen_body(node.consequent, str_pool)

        if node.alternate:
            self._emit_instr(f'BRANCH {end_lbl}', 'if: jump to endif')
            self._emit_label(else_lbl)
            self._gen_body(node.alternate, str_pool)
        else:
            self._emit_label(else_lbl)

        self._emit_label(end_lbl)

    def _gen_begin_until(self, node: BeginUntil, str_pool: list):
        top_lbl = self._fresh_label('begin')
        self._emit_label(top_lbl)
        self._gen_body(node.body, str_pool)
        self._emit_instr(f'ZBRANCH {top_lbl}',
                         'until: loop if top-of-stack is zero (false)')

    def _gen_begin_while_repeat(self, node: BeginWhileRepeat, str_pool: list):
        top_lbl = self._fresh_label('begin')
        end_lbl = self._fresh_label('repeat')
        self._emit_label(top_lbl)
        self._gen_body(node.test, str_pool)
        self._emit_instr(f'ZBRANCH {end_lbl}', 'while: exit if zero (false)')
        self._gen_body(node.body, str_pool)
        self._emit_instr(f'BRANCH {top_lbl}', 'repeat: unconditional jump back')
        self._emit_label(end_lbl)

    def _gen_do_loop(self, node: DoLoop, str_pool: list):
        top_lbl  = self._fresh_label('do')
        end_lbl  = self._fresh_label('loop')
        step_fn  = 'vm_plus_loop_step' if node.plus_loop else 'vm_do_loop_step'
        self._emit_instr('TWOTOR', 'do: push limit and index to R')
        self._emit_label(top_lbl)
        self._gen_body(node.body, str_pool)
        self._emit_instr(f'CALL {step_fn}',      'loop: increment and test')
        self._emit_instr(f'ZBRANCH {top_lbl}',   'loop: branch if not done')
        self._emit_instr('TWORFROM', 'loop: discard limit and index from R')
        self._emit_instr('CALL _2drop',          'loop: drop limit and index')
        self._emit_label(end_lbl)

    # ------------------------------------------------------------------
    # String label helper
    # ------------------------------------------------------------------

    def _fresh_str_label(self) -> str:
        self._str_count += 1
        return f'_str_{self._str_count:04d}'

